# name of the workflow
name: Build and Deploy FastAPI Code

# specify when should the CI/CD be triggered
# triggered on push and pull requests in main branch only
# to trigger on all branches -> on : [push, pull_request]
on:
  push:
    branches:
      - "main"
    # - "next_branch" and so on..
  pull_request:
    branches:
      - "main"

# provide list of jobs to be done on the runner
jobs:
  job1: 
    # specify the os
    runs-on: ubuntu-latest
    # specify the steps
    steps:
        # name -> human readable discription of the step
        # uses -> the github action to be performed
      - name: Pulling git repo
        uses: actions/checkout@v2
      - name: Install python3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install all dependencies
        run: pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest
          pytest 
        
